## Everything in this file gets sourced during `simInit()`,
## and all functions and objects are put into the `simList`.
## To use objects, use `sim$xxx` (they are globally available to all modules).
## Functions can be used without `sim$` as they are namespaced to the module,
## just like functions in R packages.
## If exact location is required, functions will be: `sim$<moduleName>$FunctionName`.
defineModule(sim, list(
  name = "Biomass_fireWeather",
  description = paste("A module that reads weather data tables and converts them to appropriate rasters. Conceived to read",
                      "data generated by BioSim and make rasters for each variable, based on the input DEM used by BioSIM.",
                      "At the moment, it produces rasters needed by LandR module Biomass_fireProperties."),
  keywords = c("weather", "climate", "data munging", "BioSIM"),
  authors = person("Ceres", "Barros", email = "cbarros@mail.ubc.ca", role = c("aut", "cre")),
  childModules = character(0),
  version = numeric_version("0.0.1"),
  spatialExtent = raster::extent(rep(NA_real_, 4)),
  timeframe = as.POSIXlt(c(NA, NA)),
  timeunit = "year",
  citation = list("citation.bib"),
  documentation = list("README.txt", "Biomass_fireWeather.Rmd"),
  reqdPkgs = list("R.utils", "raster", "data.table", "sf",
                  "PredictiveEcology/SpaDES.core@development",
                  "PredictiveEcology/SpaDES.tools@development",
                  "PredictiveEcology/reproducible@development"),
  parameters = rbind(
    defineParameter(".plotInterval", "numeric", 1, NA, NA, "This describes the simulation time interval between plot events"),
    defineParameter(".useCache", "logical", "init", NA, NA,
                    desc = "use caching for the spinup simulation?")
  ),
  inputObjects = bind_rows(
    expectsInput(objectName = "DEMRas", objectClass = "RasterLayer",
                 desc = "Digital elevation model (DEM) raster used by the weather generator to make 'weatherTable'",
                 sourceURL = "https://drive.google.com/file/d/1Fosf9xfD4UmljwZCxH7MHqsO9EtK4nvp/view?usp=sharing"),
    expectsInput(objectName = "weatherTable", objectClass = "data.table",
                 desc = "Weather data output by the weather generator, to be imported and converted to a raster",
                 sourceURL = "https://drive.google.com/file/d/16Oe8iN1QWRaG9QuiL1alsr3PYzdmff_K/view?usp=sharing"),
  ),
  outputObjects = bind_rows(
    createsOutput(objectName = "precipitationRas", objectClass = "RasterLayer",
                  desc = paste("Raster of total daily precipitation values (Jun-Aug). Defaults to BioSIM-generated values,",
                               "for using Canada-US climate normals 1961-1990 available at",
                               "ftp://ftp.cfl.scf.rncan.gc.ca/regniere/Data11/Weather/Normals/past/Canada-USA_1961-1990.zip")),
    createsOutput(objectName = "relativeHumRas", objectClass = "RasterLayer",
                  desc = paste("Raster of daily relative humidity values (Jun-Aug). Defaults to BioSIM-generated values,",
                               "for using Canada-US climate normals 1961-1990 available at",
                               "ftp://ftp.cfl.scf.rncan.gc.ca/regniere/Data11/Weather/Normals/past/Canada-USA_1961-1990.zip")),
    createsOutput(objectName = "temperatureRas", objectClass = "RasterLayer",
                  desc = paste("Raster of daily mean air temperature values (Jun-Aug). Defaults to BioSIM-generated values,",
                               "for using Canada-US climate normals 1961-1990 available at",
                               "ftp://ftp.cfl.scf.rncan.gc.ca/regniere/Data11/Weather/Normals/past/Canada-USA_1961-1990.zip")),
    createsOutput(objectName = "windSpeedRas", objectClass = "RasterLayer",
                  desc = paste("Raster of daily mean wind speed at 10m (Jun-Aug). Defaults to BioSIM-generated values,",
                               "for using Canada-US climate normals 1961-1990 available at",
                               "ftp://ftp.cfl.scf.rncan.gc.ca/regniere/Data11/Weather/Normals/past/Canada-USA_1961-1990.zip"))
  )
))

## event types
#   - type `init` is required for initialization

doEvent.Biomass_fireWeather = function(sim, eventTime, eventType) {
  switch(
    eventType,
    init = {
      ### check for more detailed object dependencies:
      ### (use `checkObject` or similar)

      # do stuff for this event
      sim <- Init(sim)

      # schedule future event(s)
      sim <- scheduleEvent(sim, P(sim)$.plotInitialTime, "Biomass_fireWeather", "plot")
      sim <- scheduleEvent(sim, P(sim)$.saveInitialTime, "Biomass_fireWeather", "save")
    },
    event1 = {

    },
    warning(paste("Undefined event type: \'", current(sim)[1, "eventType", with = FALSE],
                  "\' in module \'", current(sim)[1, "moduleName", with = FALSE], "\'", sep = ""))
  )
  return(invisible(sim))
}

## event functions
#   - keep event functions short and clean, modularize by calling subroutines from section below.

### template initialization
Init <- function(sim) {
  # # ! ----- EDIT BELOW ----- ! #

  # ! ----- STOP EDITING ----- ! #

  return(invisible(sim))
}

### template for your event1
Event1 <- function(sim) {
  # ! ----- EDIT BELOW ----- ! #
  # THE NEXT TWO LINES ARE FOR DUMMY UNIT TESTS; CHANGE OR DELETE THEM.
  # sim$event1Test1 <- " this is test for event 1. " # for dummy unit test
  # sim$event1Test2 <- 999 # for dummy unit test

  # ! ----- STOP EDITING ----- ! #
  return(invisible(sim))
}

.inputObjects <- function(sim) {
  cacheTags <- c(currentModule(sim), "function:.inputObjects")
  dPath <- asPath(getOption("reproducible.destinationPath", dataPath(sim)), 1)
  message(currentModule(sim), ": using dataPath '", dPath, "'.")

  if (!suppliedElsewhere("weatherTable", sim)) {
    sim$weatherTable <- Cache(prepInputs, targetFile = "Export (WeatherGeneration).csv",
                              archive = "DailyClimatic_CA-USnormals_1961-1990.zip",
                              fun = "read.csv",
                              destinationPath = dPath,
                              url = extractURL("weatherTable", sim),
                              userTags = c(cacheTags, "weatherTable"),
                              omitArgs = "userTags")
  }

  if (!suppliedElsewhere("DEMRas", sim)) {
    sim$DEMRas <- Cache(prepInputs, targetFile = "DEM1kmRes.tif",
                        archive = "DEMraster.zip",
                        destinationPath = dPath,
                        url = extractURL("DEMRas", sim),
                        userTags = c(cacheTags, "DEMRas"),
                        omitArgs = "userTags")
  }

  return(invisible(sim))
}

### add additional events as needed by copy/pasting from above
