---
title: "General publication plots"
author: "Ceres Barros"
date: "18/11/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = normalizePath(getwd()))
knitr::opts_chunk$set(echo = FALSE, cache = 2, warning = FALSE,
                      fig.width = 10, fig.height = 8)

```


```{r setup2, include=FALSE}
if (!exists("pkgDir")) {
  pkgDir <- file.path(
    if (Sys.info()[["user"]] == "rstudio") "packages_docker" else "packages",
    version$platform,
    paste0(version$major, ".", strsplit(version$minor, "[.]")[[1]][1])
  )
  
  if (!dir.exists(pkgDir)) {
    dir.create(pkgDir, recursive = TRUE)
  }
  .libPaths(pkgDir)
}

library(Require)

Require(
  c("cowplot",
    "data.table",
    "ggplot2",
    "ggpubr",
    "ggspatial",
    "magick",
    "paletteer",
    "purrr",
    "qs",
    "raster",
    "SpaDES"),
  install = FALSE)

source("R/R_tools/plotFunction.R")
source("R/R_tools/convertToCNVegType.R")
source("R/R_tools/Useful_functions.R")
options("reproducible.useNewDigestAlgorithm" = 2)
options("spades.moduleCodeChecks" = FALSE)
options("reproducible.useCache" = TRUE)
options("reproducible.destinationPath" = normPath("R/SpaDES/inputs"))
options("reproducible.useGDAL" = FALSE)

## general paths
simDirName <- "mar2022Runs"
if (Sys.info()["nodename"] == "W-VIC-A127584") {
  simPaths <- list(cachePath = file.path("F:", basename(getwd()), "R/SpaDES/cache", simDirName, "postSimAnalyses")
                   , modulePath = normPath(file.path("R/SpaDES/m"))
                   , inputPath = normPath(file.path("R/SpaDES/inputs"))
                   , outputPath = file.path("F:", basename(getwd()), "R/SpaDES/outputs", simDirName))
} else if (grepl("for-cast", Sys.info()["nodename"])) {
  simPaths <- list(cachePath = file.path("R/SpaDES/cache", simDirName, "postSimAnalyses")
                   , modulePath = normPath(file.path("R/SpaDES/m"))
                   , inputPath = normPath(file.path("R/SpaDES/inputs"))
                   , outputPath = normPath(file.path("R/SpaDES/outputs", simDirName))
                   , rasterPath = file.path("/mnt/scratch/cbarros", basename(getwd()), "R/SpaDES/scratch/raster")
                   , scratchPath = file.path("/mnt/scratch/cbarros", basename(getwd()), "R/SpaDES/scratch"))
} else {
  simPaths <- list(cachePath = normPath(file.path("R/SpaDES/cache", simDirName, "postSimAnalyses"))
                   , modulePath = normPath(file.path("R/SpaDES/m"))
                   , inputPath = normPath(file.path("R/SpaDES/inputs"))
                   , outputPath = normPath(file.path("R/SpaDES/outputs", simDirName)))
}

if (grepl("for-cast", Sys.info()["nodename"]) ||
    grepl("45eafed436c8", Sys.info()["nodename"])) {
  data.table::setDTthreads(5)
  options(bitmapType="cairo")
}

## path to figure folder and cache folder
figOutputPath <- file.path(simPaths$outputPath, "figuresGeneral")
dir.create(figOutputPath, recursive = TRUE)
```

### DATA LOADING AND PROCESSING NOTES
```{r dataPrep, include = FALSE, cache = FALSE}
## load one preSimulation simList - doesn't matter which one, because the objects we need are identical between scenarios.
## load one of the preSim lists to get maps, species traits and end(sim)
if (paste0(version$major, ".", strsplit(version$minor, "[.]")[[1]][1]) != "4.1") {
  warning("Simulations were run and saved with R v4.1 -- attempting to load simList with qread")
  preSimList <- qs::qread(file.path(simPaths$outputPath, "LIM_preSimulation.qs"))
} else
  preSimList <- loadSimList(file.path(simPaths$outputPath, "LIM_preSimulation.qs"))
```

### FIRE LOCATIONS AND IGNITIONS MAP
```{r fireLocations}

## this is no longer necessary (after 2022)
## to get the ignitions map, we need to run the first year of a spades call
# simOutFS <- spades(preSimList, events = c("init", "run"))

## this includes fire locations in the extent of SA but not within the polygon, so we need to 'mask'
fireLocations <- sf::st_intersection(preSimList$fireLocations, sf::st_as_sf(preSimList$studyArea))

fireLocationsPlot <- ggplot() +
  layer_spatial(data = preSimList$fireSense_IgnitionPredicted) +
  layer_spatial(data = fireLocations, colour = "darkred") +
  scale_fill_distiller(palette = "Greys", na.value = "transparent", direction = 1) +
  annotation_north_arrow(style = north_arrow_minimal,
                         location = "tr", which_north = "true") +
  theme_pubr(margin = FALSE, legend = "right") +
  labs(x = "longitude", y = "latitude", fill = expression(lambda))

fireLocationsPlot

ggsave(file.path(figOutputPath, "fireLocations.tiff"), fireLocationsPlot,
       width = 4, height = 7, dpi = 300)
```

### FUEL TYPES 
```{r fuelTypes}
rasFuels <- setValues(raster(preSimList$fuelTypesMaps$finalFuelType),
                      getValues(preSimList$fuelTypesMaps$finalFuelType))
FTlabs <- raster::levels(preSimList$fuelTypesMaps$finalFuelType)[[1]][,2]
names(FTlabs) <- raster::levels(preSimList$fuelTypesMaps$finalFuelType)[[1]][,1]

FTlabs <- sub("O1b", "O1b: Grass - Standing", FTlabs)
FTlabs <- sub("NF", "NF: Non-fuel", FTlabs)
FTlabs <- sub("C2", "C2: Boreal spruce", FTlabs)
FTlabs <- sub("C3", "C3: Mature Jack or Lodgepole pine", FTlabs)
FTlabs <- sub("C4", "C4: Immature Jack or Lodgepole pine", FTlabs)
FTlabs <- sub("C7", "C7: Ponderosa pine/Douglas-fir", FTlabs)
FTlabs <- sub("M2", "M2: Boreal mixedwood – green", FTlabs)
FTlabs <- sub("D2", "D2: Green Aspen", FTlabs)

## note that NA areas to the East are mostly cropland (class 15 in LCC2010)
## these were not included
# https://www.cec.org/files/atlas_layers/1_terrestrial_ecosystems/1_01_4_land_cover_2010_250m/metadata.zip

fuelTypesPlot <- ggplot() +
  layer_spatial(rasFuels, aes(fill = after_stat(band1))) +
  layer_spatial(data = preSimList$studyArea, fill = "transparent", colour = "black") +
  annotation_north_arrow(style = north_arrow_minimal,
                         location = "tr", which_north = "true") +
  theme_pubr(legend = "right", margin = FALSE) +
  scale_fill_distiller(palette = "Paired", breaks = sort(unique(rasFuels[])),
                       na.value = "transparent", guide = "legend",
                       labels = FTlabs) +
  labs(x = "longitude", y = "latitude", fill = "Fuel type") +
  guides(fill = guide_legend(ncol = 1))

fuelTypesPlot

ggsave(file.path(figOutputPath, "fuelsMap.tiff"), fuelTypesPlot,
       width = 7, height = 7, dpi = 300)
```

### FUEL TYPE COVER
```{r fuelTypeCover}
plotList <- lapply(unstack(preSimList$fuelTypesCoverStk), plotFunction,
                   studyArea = preSimList$studyArea, limits = c(0,1))
fuelTypesCover <- ggarrange(plotlist = plotList, ncol = 3, nrow = 3,
                            legend = "bottom", common.legend = TRUE)

fuelTypesCover

ggsave(file.path(figOutputPath, "Fueltype_cover.tiff"), fuelTypesCover,
       width = 10, height = 18, dpi = 300)
```

### TOPO, VEG, CLIMATE MAPS
```{r topoVegClim, fig.show='hold'}
## elevation
## if simLists are from experiment(), they will have no objects.
if (!is.null(preSimList$DEMRas)) {
  if (!inMemory(preSimList$DEMRas)) {
    DEMRas <- sub(".*LandscapesInMotion/", "",
                  normPath(filename(preSimList$DEMRas)))
    DEMRas <- raster(DEMRas)
  } else
    DEMRas <- preSimList$DEMRas
} else {
  tempDT <- as.data.table(showCache(cachePath(preSimList), "DEMRas"))
  DEMRas <- unique(tempDT[createdDate == max(createdDate)]$cacheId) %>%
    reproducible::loadFromCache(cachePath = cachePath(preSimList), cacheId = .)
}

elevPlot <- ggplot() +
  layer_spatial(DEMRas, aes(fill = stat(band1))) +
  layer_spatial(data = preSimList$studyArea, col = "black",
                fill = "transparent") +
  annotation_north_arrow(style = north_arrow_minimal,
                         height = unit(1, "cm"), width = unit(1, "cm"),
                         location = "tr", which_north = "true") +
  theme_pubr(legend = "right") +
  theme(plot.margin = unit(c(0,0,0,0), units = "mm")) +
  scale_fill_distiller(palette = "Spectral", na.value = "transparent",
                       direction = -1) +
  labs(x = "longitude", y = "latitude", fill = "m a.s.l.",
       title = "Elevation")

elevPlot

## stand biomass (after imputation as adjustments)
biomassRas <- SpaDES.tools::rasterizeReduced(preSimList$cohortData[, list(standB = sum(B)), by = pixelGroup],
                                             fullRaster = preSimList$pixelGroupMap,
                                             newRasterCols = "standB", mapcode = "pixelGroup")

biomassPlot <- ggplot() +
  layer_spatial(log(biomassRas), aes(fill = stat(band1))) +
  layer_spatial(data = preSimList$studyArea, col = "black",
                fill = "transparent") +
  annotation_north_arrow(style = north_arrow_minimal,
                         height = unit(1, "cm"), width = unit(1, "cm"),
                         location = "tr", which_north = "true") +
  theme_pubr(legend = "right") +
  theme(plot.margin = unit(c(0,0,0,0), units = "mm")) +
  scale_fill_distiller(palette = "Greens", na.value = "transparent",
                       direction = 1) +
  labs(x = "longitude", y = "latitude", fill = expression(atop("g/m"^2,"(log scale)")),
       title = "Stand biomass")

biomassPlot

## Stand age - after corrections/imputation
ageRas <- SpaDES.tools::rasterizeReduced(unique(preSimList$cohortData[, .(pixelGroup, age)]),
                                         fullRaster = preSimList$pixelGroupMap,
                                         newRasterCols = "age", mapcode = "pixelGroup")
agePlot <- ggplot() +
  layer_spatial(ageRas, aes(fill = stat(band1))) +
  layer_spatial(data = preSimList$studyArea, col = "black",
                fill = "transparent") +
  annotation_north_arrow(style = north_arrow_minimal,
                         height = unit(1, "cm"), width = unit(1, "cm"),
                         location = "tr", which_north = "true") +
  theme_pubr(legend = "right") +
  theme(plot.margin = unit(c(0,0,0,0), units = "mm")) +
  scale_fill_distiller(palette = "Greens", na.value = "transparent",
                       direction = 1) +
  labs(x = "longitude", y = "latitude", fill = "years",
       title = "Stand age")

agePlot

## meanMDC
if (!is.null(preSimList$fireSense_IgnitionAndEscapeCovariates$meanMDC)) {
  if (!inMemory(preSimList$fireSense_IgnitionAndEscapeCovariates$meanMDC)) {
    meanMDCRas <- sub(".*LandscapesInMotion/", "",
                      normPath(filename(preSimList$fireSense_IgnitionAndEscapeCovariates$meanMDC)))
    meanMDCRas <- raster(meanMDCRas)
  } else
    meanMDCRas <- preSimList$fireSense_IgnitionAndEscapeCovariates$meanMDC
} else {
  stop("can't find meanMDC raster")
}

meanMDCPlot <- ggplot() +
  layer_spatial(meanMDCRas, aes(fill = stat(band1))) +
  layer_spatial(data = preSimList$studyArea, col = "black",
                fill = "transparent") +
  annotation_north_arrow(style = north_arrow_minimal,
                         height = unit(1, "cm"), width = unit(1, "cm"),
                         location = "tr", which_north = "true") +
  theme_pubr(legend = "right") +
  theme(plot.margin = unit(c(0,0,0,0), units = "mm")) +
  scale_fill_distiller(palette = "RdYlBu", na.value = "transparent",
                       direction = -1) +
  labs(x = "longitude", y = "latitude", fill = "MDC",
       title = "Mean monthly drought code (MDC)")

meanMDCPlot

plotSave <- ggarrange(elevPlot, agePlot, biomassPlot, meanMDCPlot, ncol = 2, nrow = 2)
ggsave(file.path(figOutputPath, "elev_StandAge_B_MDC.tiff"), plotSave,
       width = 10, height = 14, dpi = 300)

```

### SPECIES COVER MAPS 
```{r sppLayers}
## For some reason these layers have no names
# if (!is.null(preSimList$speciesLayers)){
#   if (!inMemory(preSimList$speciesLayers)) {
#     sppStkFiles <- sub(".*LandscapesInMotion/", "",
#                        sapply(unstack(preSimList$speciesLayers), function(x) normPath(filename(x))))
#     sppStk <- stack(sppStkFiles)
#     names(sppStk) <- sub(".*\\.", "", sub(".tif", "", basename(sppStkFiles)))
#   } else
#     sppStk <- preSimList$speciesLayers
# }  else {
#   tempDT <- as.data.table(showCache(cachePath(preSimList), "speciesLayers"))
#   sppStk <- unique(tempDT[createdDate == max(createdDate)]$cacheId) %>%
#     reproducible::loadFromCache(cachePath = cachePath(preSimList), cacheId = .)
# }

sppStk <- stack(file.path("R/SpaDES/outputs", simDirName, "PM/speciesLayers_NA.grd"))

names(sppStk) <- LandR::equivalentName(value = names(sppStk), column = "EN_generic_full",
                                       df = preSimList$sppEquiv)

## mask spp layers to remove 0s around SA
sppStk <- mask(sppStk, ageRas)

plotList <- lapply(unstack(sppStk), plotFunction,
                   palette = "Greens",
                   studyArea = preSimList$studyArea, limits = c(0, 100))
plotSave <- ggarrange(plotlist = plotList, ncol = 3, nrow = 2,
                      legend = "bottom", common.legend = TRUE)

ggsave(file.path(figOutputPath, "Species_cover.tiff"), plotSave,
       width = 11, height = 14, dpi = 300)
```


## ECOREGIONS AND LAND COVER
```{r ecoregionLC}
## ECOREGIONS ---------------------------
## ecological zones
if (!is.null(preSimList$ecoregionLayer)) {
  ecoDistSF <- sf::st_as_sf(preSimList$ecoregionLayer)
} else {
  tempDT <- as.data.table(showCache(cachePath(preSimList), "ecoregionLayer"))
  ecoDistSF <- unique(tempDT[createdDate == max(createdDate)]$cacheId) %>%
    reproducible::loadFromCache(cachePath = cachePath(preSimList), cacheId = .) %>%
    sf::st_as_sf(.)
}

ecoDistSF$ecozoneCode2 <- factor(paste(ecoDistSF$NRNAME, ecoDistSF$NSRNAME, sep = " - "))

ecoDistPlot <- ggplot(ecoDistSF) +
  # geom_sf(data = alberta) +
  geom_sf(data = ecoDistSF, aes(fill = ecozoneCode2)) +
  layer_spatial(data = preSimList$studyArea, fill = "transparent", colour = "black") +
  scale_fill_brewer(palette = "RdYlGn", direction = 1) +
  annotation_north_arrow(style = north_arrow_minimal,
                         height = unit(1, "cm"), width = unit(1, "cm"),
                         location = "tr", which_north = "true") +
  theme_pubr(legend = "right", base_size = 16) +
  theme(plot.margin = margin(0,0,0,0, unit = "mm")) +
  labs(x = "longitude", y = "latitude", fill = "",
       title = "Natural Regions and Subregions of Alberta")

## land-cover classes
if (!is.null(preSimList$rstLCCRTM)) {
  if (!inMemory(preSimList$rstLCCRTM)) {
    lccRas <- sub(".*LandscapesInMotion/", "",
                  normPath(filename(preSimList$rstLCCRTM)))
    lccRas <- raster(lccRas)
  } else
    lccRas <- preSimList$rstLCCRTM
} else {
  tempDT <- as.data.table(showCache(cachePath(preSimList), "rstLCCRTM"))
  lccRas <- unique(tempDT[createdDate == max(createdDate)]$cacheId) %>%
    reproducible::loadFromCache(cachePath = cachePath(preSimList), cacheId = .)
}

lccRas[lccRas[] == 0] <- NA

## get original lcc, for colortable
tempLCC <- raster("R/SpaDES/inputs/CAN_LC_2010_CAL.tif")
colortable(lccRas) <- colortable(tempLCC)
rm(tempLCC)

## commented bits were the full legend title

## LCC 2005
# lccLabels <- c("Temperate/subpolar needle-leaved evergreen", #, closed canopy",
#                "Cold deciduous closed canopy",
#                "Mixed needle-leaved evergreen", #, > deciduous closed canopy",
#                "Mixed needle-leaved evergreen, young", #, > deciduous closed young canopy",
#                "Mixed cold deciduous", # > needle-leaved evergreen closed canopy",
#                "Temperate/subpolar needle-leaved evergreen, medium density", # moss-shrub",
#                "Temperate/subpolar needle-leaved evergreen", #, medium density, lichen-shrub",
#                "Temperate/subpolar needle-leaved evergreen, low density", #, moss-shrub",
#                "Temperate/subpolar needle-leaved evergreen", #, low density, lichen-rock",
#                "Temperate/subpolar needle-leaved evergreen, poor drain.", #, low density, poorly drained",
#                "Cold deciduous broadleaved", #,, low-medium density",
#                "Cold deciduous broadleaved, young", #,, medium density, young regenerating",
#                "Mixed needle-leaved evergreen > deciduous", #,, low-medium density",
#                "Mixed needle-leaved deciduous > evergreen", #,, low-medium density",
#                "Low regenerating young mixed cover",
#                "High-low shrub dominated",
#                "Grassland",
#                "Herb-shrub-bare cover",
#                "Wetlands",
#                "Sparse needle-leaved evergreen", #,, herb-shrub cover",
#                "Polar grassland, herb-shrub",
#                "Shrub-herb-lichen-bare",
#                "Herb-shrub poorly drained",
#                "Lichen-shrub-herb-bare soil",
#                "Low vegetation cover",
#                "Cropland-woodland",
#                "High biomass cropland",
#                "Medium biomass cropland",
#                "Low biomass cropland",
#                "Lichen barren",
#                "Lichen-sedge-moss-low shrub wetland",
#                "Lichen-spruce bog",
#                "Rock outcrops",
#                "Recent burns",
#                "Old burns",
#                "Urban and built-up",
#                "Water bodies",
#                "Mixes of water and land",
#                "Snow/ice")
#
# lccLabels <- paste(as.character(seq_along(lccLabels)),
#                    lccLabels, sep = " - ")

## LCC 2010

lccLabels <- c("1 - Temperate or sub-polar needleleaf forest",
               "2 - Sub-polar taiga needleleaf forest",
               "3 - Tropical or sub-tropical broadleaf evergreen forest",
               "4 - Tropical or sub-tropical broadleaf deciduous forest",
               "5 - Temperate or sub-polar broadleaf deciduous forest",
               "6 - Mixed Forest",
               "7 - Tropical or sub-tropical shrubland",
               "8 - Temperate or sub-polar shrubland",
               "9 - Tropical or sub-tropical grassland",
               "10 - Temperate or sub-polar grassland",
               "11 - Sub-polar or polar shrubland-lichen-moss",
               "12 - Sub-polar or polar grassland-lichen-moss",
               "13 - Sub-polar or polar barren-lichen-moss",
               "14 - Wetland",
               "15 - Cropland",
               "16 - Barren lands",
               "17 - Urban",
               "18 - Water",
               "19 - Snow and Ice")
names(lccLabels) <- as.character(seq_along(lccLabels))

## colour vector -- filter to existing values only
lccColours <- colortable(lccRas)
if (length(lccColours)) {
  names(lccColours) <- names(lccLabels)
  lccColours <- lccColours[as.character(na.omit(unique(getValues(lccRas))))]
} else {
  lccColours <- c("#006064FF",
                  "#009688FF",
                  "lightgreen",
                  "chartreuse",
                  "#4CAF50FF",
                  "#8BC34AFF",
                  "forestgreen",
                  "#FF9800FF",
                  "#29B6F6FF",
                  "#FFEB3BFF",
                  "#3F51B5FF",
                  "#2196F3FF",
                  "#673AB7FF",
                  "#9C27B0FF",
                  "#C62828FF",
                  "#795548FF",
                  "#9E9E9EFF",
                  "#607D8BFF",
                  "white")
  names(lccColours) <- names(lccLabels)
}

# lccLabels <-  lccLabels[names(lccLabels) %in% unique(lccRas[])]
## plot using DT
rasData <- data.table(coordinates(lccRas), vals = as.factor(getValues(lccRas)))
lccPlot <- ggplot() +
  geom_raster(data = rasData, mapping = aes(x, y, fill = vals)) +
  layer_spatial(data = preSimList$studyArea, col = "black",
                fill = "transparent") +
  annotation_north_arrow(style = north_arrow_minimal,
                         height = unit(1, "cm"), width = unit(1, "cm"),
                         location = "tr", which_north = "true") + 
  scale_fill_manual(values = lccColours, na.value = "transparent",
                    labels = lccLabels, 
                    breaks = sort(as.integer(names(lccLabels)))) +
  theme_pubr(legend = "right", base_size = 16) +
  theme(plot.margin = margin(0,0,0,0.5, unit = "mm"),
        legend.key = element_rect(colour = "black")) +
  labs(x = "longitude", y = "latitude", fill = "",
       title = "Land cover") +
  guides(fill = guide_legend(ncol = 1))

plotSave <- ggarrange(ecoDistPlot, lccPlot, ncol = 2, nrow = 1,
                      widths = c(0.7,1), labels = "auto",
                      font.label = list(size = 20))
ggsave(file.path(figOutputPath, "Ecologicalzones_LCC.tiff"), plotSave,
       width = 19, height = 10, dpi = 300)

ggsave(file.path(figOutputPath, "LCC.tiff"), lccPlot + theme(legend.position = "right"),
       width = 11, height = 11, dpi = 300)

```

## STUDY AREA WITHIN PROVINCE
```{r studyArea}
canada <- sf::st_as_sf(shapefile("data/CA_admin/gpr_000a11a_e.shp"))
canada <- sf::st_transform(canada, crs = crs(ecoDistSF))
alberta <- canada[canada$PRENAME %in% "Alberta",]

## STUDY AREA IN ALBERTA ---------------------------
SAPlot <- ggplot() +
  geom_sf(data = alberta) +
  layer_spatial(data = preSimList$studyArea, fill = "forestgreen", colour = "black") +
  annotation_north_arrow(style = north_arrow_minimal,
                         height = unit(1, "cm"), width = unit(1, "cm"),
                         location = "tr", which_north = "true") +
  theme_pubr(legend = "right") +
  theme(plot.background = element_rect(fill = "transparent")) +
  labs(x = "longitude", y = "latitude",
       title = "Study area")

ggsave(file.path(figOutputPath, "LIM_studyArea.tiff"), SAPlot,
       width = 4, height = 7, dpi = 300)



## make a second SAplot with no north arrow and no title
SAPlot2 <- ggplot() +
  geom_sf(data = alberta) +
  layer_spatial(data = preSimList$studyArea, fill = "forestgreen", colour = "black") +
  theme_void() +
  theme(plot.background = element_rect(fill = "transparent", colour = "transparent"), title = element_blank()) +
  labs(x = "longitude", y = "latitude")

insetMap <- ggdraw() +
  draw_plot(ecoDistPlot + 
              theme(title = element_blank(), legend.position = "bottom") +
              guides(fill = guide_legend(ncol = 2))) +
  draw_plot(SAPlot2,
            x = 0.75, y = 0.7, 
            width = 0.3, height = 0.3)
ggsave(plot = insetMap, filename = file.path(figOutputPath, "Ecologicalzones_inset.tiff"), bg = "white",
       width = 9, height = 10, units = "in", dpi = 300)
```


```{r GIFsdataprep}
outputs_PM <- list.dirs(simPaths$outputPath, full.names = TRUE, recursive = TRUE) %>%
  grep("/PM_rep[[:digit:]]{1,2}$", ., value = TRUE)
outputs_noPM <- list.dirs(simPaths$outputPath, full.names = TRUE, recursive = TRUE) %>%
  grep("/noPM_rep[[:digit:]]{1,2}$", ., value = TRUE)

vegTypeMapFiles <- c(sapply(outputs_PM, FUN = function(x) list.files(x, pattern = "vegTypeMap", full.names = TRUE)),
                     sapply(outputs_noPM, FUN = function(x) list.files(x, pattern = "vegTypeMap", full.names = TRUE))) %>%
  unique(.)

vegTypeMapStk_noPM <- lapply(grep("noPM", vegTypeMapFiles, value = TRUE), readRDS) %>%
  stack(.)
vegTypeMapStk_PM <- lapply(grep("noPM", vegTypeMapFiles, value = TRUE, invert = TRUE), readRDS) %>%
  stack(.)
names(vegTypeMapStk_noPM) <- sub(".*year", "year", sub("\\.rds", "", grep("noPM", vegTypeMapFiles, value = TRUE)))
names(vegTypeMapStk_PM) <- sub(".*year", "year", sub("\\.rds", "", grep("noPM", vegTypeMapFiles, invert = TRUE, value = TRUE)))


speciesLabels <- LandR::equivalentName(value = levels(vegTypeMapStk_noPM[[1]])[[1]]$VALUE,
                                       column = "EN_generic_full", df = preSimList$sppEquiv)
names(speciesLabels) <- unique(levels(vegTypeMapStk_noPM[[1]])[[1]]$ID)

speciesColours <- levels(vegTypeMapStk_noPM[[1]])[[1]]$colors
names(speciesColours) <- levels(vegTypeMapStk_noPM[[1]])[[1]]$ID

foothillsMask <- DEMRas
foothillsMask[!is.na(foothillsMask[])] <- 1
foothillsMaskDF <- as.data.frame(as(foothillsMask, "SpatialPixelsDataFrame"))
names(foothillsMaskDF) <- c("value", "x", "y")
``` 

```{r GIFsdataprep}
makePNGs <- function(id, rasterStack, labPrefix, labSufix, filePrefix, gif.dir) {
  suppressWarnings(dir.create(gif.dir, recursive = TRUE))
  cat("Making ", id, "\n")
  rasterVis::gplot(rasterStack[[id]],
                   maxpixels = ncell(rasterStack[[id]])) +
    geom_tile(data = foothillsMaskDF,
              aes(x = x, y = y), fill = "grey95") +
    geom_tile(aes(fill = as.factor(value))) +
    scale_fill_manual(values = speciesColours,
                      labels = speciesLabels) +
    theme_void() + theme(legend.position = "none", text = element_text(size = 20)) +
    labs(title = paste(labPrefix, sub("year", "year ", names(rasterStack)[id]), labSufix, sep = "")) +
    coord_equal()
  ggsave(file.path(gif.dir, paste0(filePrefix, id, ".png")),
         device = "png", width=5, height=10, dpi = 300, units = "in")
  return(NULL)
}


map_df(.x = seq(1, nlayers(vegTypeMapStk_noPM), 100), .f = makePNGs,
       rasterStack = vegTypeMapStk_noPM,
       labPrefix = "stand replacement\n",
       labSufix = "",
       filePrefix = "vegTypeMapStk_noPM",
       gif.dir = file.path(figOutputPath, "gifs", "noPM_rep1"))
map_df(.x = seq(1, nlayers(vegTypeMapStk_PM), 100), .f = makePNGs,
       rasterStack = vegTypeMapStk_PM,
       labPrefix = "partial mortality\n",
       labSufix = "",
       filePrefix = "vegTypeMapStk_PM",
       gif.dir = file.path(figOutputPath, "gifs", "PM_rep1"))

makeGIF <- function(gif.dir, gifPrefix, ...) {
  ## get file list and the file numbers (to sort numerically, rather than alphabetically)
  PNGlist <- list.files(path = gif.dir, pattern = "*.png")
  fileNos <- as.numeric(sub("\\.png", "", sub("^\\D*(\\d)", "\\1", PNGlist)))
  
  ## make GIF
  file.path(gif.dir, PNGlist[order(fileNos)]) %>%
    map(image_read) %>% # reads each path file
    image_join() %>% # joins image
    image_animate(...) %>% # animates, can opt for number of loops
    image_write(file.path(gif.dir, paste0(gifPrefix, ".gif")))
  
  if (file.exists(file.path(gif.dir, paste0(gifPrefix, ".gif"))))
    file.remove(PNGlist)
}

makeGIF(gif.dir = file.path(figOutputPath, "gifs", "noPM_rep1"),
        gifPrefix = "vegTypeMapStk_noPM",
        fps = 2)
makeGIF(gif.dir = file.path(figOutputPath, "gifs", "PM_rep1"),
        gifPrefix = "vegTypeMapStk_PM",
        fps = 2)

```


